#!/bin/bash

readonly rootdir=/home/gabor/Development/Workspaces/C/Test02/cgi-bin
readonly templatedir=${rootdir}/templates

function render {
  cat ${templatedir}/$1 | ${rootdir}/mo
}

function main {
  echo "Content-type: text/html"
  echo ""
  export USER="World"
  export PAGE_TITLE="Index"
  render index.template
}

main
